pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                echo 'Checking out code from private GitHub repository...'
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/master']], // Adjust branch name if needed
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    userRemoteConfigs: [[
                        url: 'https://github.com/koukaa-500/MusicClassifier.git',
                        credentialsId: "1"
                    ]]
                ])
            }
        }
        stage('Build Frontend') {
            steps {
                script {
                    dir('frontend') {
                        bat 'docker build -t front .'
                    }
                }
            }
        }
        stage('Build SVM') {
            steps {
                script {
                    dir('Backend/SVM') {
                        bat 'docker build -t svm .'
                    }
                }
            }
        }
        
        stage('Build VGG19') {
            steps {
                script {
                    dir('Backend/VGG19') {
                        bat 'docker build -t vgg19 .'
                    }
                }
            }
        }

        stage('Deploy'){
            steps{
                 script {
                    
                        bat 'docker-compose up -d'
                    
                }
            }
        }
        stage('pytest'){
            steps{
                 script {
                        bat 'pip install pytest-html'
                }
            }
        }
        // stage('Test') {
        //     steps {
        //         script {
        //             dir('Backend/SVM') {
        //                 bat 'pytest test.py --html=report.html --self-contained-html'

        //             }
        //         }
        //     }
        // }


        stage('Push front') {
             steps {
                script {
                // Login to Docker Hub using the credentials stored in Jenkins
                withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'koukaa', passwordVariable: 'nabil1234')]) {
                    bat 'echo $DOCKER_PASSWORD | docker login -u koukaa -p nabil1234'
                }
                bat 'docker tag front koukaa/frontend:latest'
                bat 'docker push koukaa/frontend:latest'

                }
             }
        }

        stage('Push svm'){
            steps{
               script {
                // Login to Docker Hub using the credentials stored in Jenkins
                withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'koukaa', passwordVariable: 'nabil1234')]) {
                    bat 'echo $DOCKER_PASSWORD | docker login -u koukaa -p nabil1234'
                }
                bat 'docker tag svm koukaa/svm_image:latest'
                bat 'docker push koukaa/svm_image:latest'
                } 
            }
        }
        stage('Push vgg19') {
             steps {
                script {
                // Login to Docker Hub using the credentials stored in Jenkins
                withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'koukaa', passwordVariable: 'nabil1234')]) {
                    bat 'echo $DOCKER_PASSWORD | docker login -u koukaa -p nabil1234'
                }                
                bat 'docker tag vgg19 koukaa/vgg19_image:latest'
                bat 'docker push koukaa/vgg19_image:latest'
                }
             }
        }

        
        
      
    }
    post {
    success {
        publishHTML([allowMissing: false,
                     alwaysLinkToLastBuild: true,
                     keepAll: true,
                     reportDir: 'Backend/SVM',
                     reportFiles: 'report.html',
                     reportName: 'Test Report'])
    }
}

}
